
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 06:44:21 KST (Jul  8 2026 21:44:21 UTC)

// Verification Directory fv/digtimer 

module seven_seg_5(num, seven_seg);
  input [3:0] num;
  output [7:0] seven_seg;
  wire [3:0] num;
  wire [7:0] seven_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_11;
  NAND4XL g302__2398(.A (n_2), .B (n_4), .C (n_0), .D (n_6), .Y
       (seven_seg[1]));
  NAND3BXL g304__6260(.AN (n_7), .B (num[2]), .C (n_2), .Y
       (seven_seg[6]));
  NAND2X1 g306__8428(.A (n_2), .B (n_9), .Y (seven_seg[7]));
  OAI211X1 g307__5526(.A0 (num[0]), .A1 (n_5), .B0 (n_2), .C0 (n_0), .Y
       (seven_seg[2]));
  AOI2BB1XL g308__6783(.A0N (n_1), .A1N (n_0), .B0 (seven_seg[3]), .Y
       (n_11));
  NAND3X1 g309__3680(.A (n_1), .B (n_2), .C (n_5), .Y (seven_seg[5]));
  AOI221X1 g310__1617(.A0 (n_1), .A1 (n_3), .B0 (num[0]), .B1 (num[2]),
       .C0 (num[1]), .Y (n_9));
  AND2XL g311__2802(.A (n_1), .B (n_0), .Y (seven_seg[3]));
  MXI2XL g312__1705(.A (num[0]), .B (n_1), .S0 (num[1]), .Y (n_7));
  INVX1 g314(.A (n_6), .Y (n_5));
  NAND2XL g315__5122(.A (n_1), .B (num[1]), .Y (n_4));
  NAND2X1 g316__8246(.A (n_3), .B (num[1]), .Y (n_6));
  INVX1 g317(.A (num[2]), .Y (n_3));
  INVX1 g319(.A (num[3]), .Y (n_2));
  INVX1 g320(.A (num[0]), .Y (n_1));
  NAND2BX1 g2__7098(.AN (num[1]), .B (num[2]), .Y (n_0));
  NAND3X1 g2(.A (n_2), .B (n_6), .C (n_11), .Y (seven_seg[4]));
endmodule

module digit_ctrl_2(clk, rst, value, fnd_data, fnd_sel);
  input clk, rst;
  input [5:0] value;
  output [7:0] fnd_data;
  output [1:0] fnd_sel;
  wire clk, rst;
  wire [5:0] value;
  wire [7:0] fnd_data;
  wire [1:0] fnd_sel;
  wire [7:0] out_ones;
  wire UNCONNECTED, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_14, n_15, n_16;
  seven_seg_5 dec_ones(.num ({n_16, n_15, n_14, value[0]}), .seven_seg
       ({out_ones[7:1], UNCONNECTED}));
  OAI2BB1X1 g1265__6131(.A0N (value[2]), .A1N (n_11), .B0 (n_12), .Y
       (n_14));
  NOR2BX1 g1266__1881(.AN (n_11), .B (value[2]), .Y (n_16));
  NOR2BX1 g1267__5115(.AN (value[2]), .B (n_11), .Y (n_15));
  NAND2BX1 g1268__7482(.AN (value[3]), .B (value[1]), .Y (n_12));
  NOR2BX1 g1269__4733(.AN (value[3]), .B (value[1]), .Y (n_11));
  DFFRHQX1 \fnd_data_reg[7] (.RN (rst), .CK (clk), .D (n_10), .Q
       (fnd_data[7]));
  DFFRHQX1 \fnd_data_reg[4] (.RN (rst), .CK (clk), .D (n_7), .Q
       (fnd_data[4]));
  DFFRHQX1 \fnd_data_reg[3] (.RN (rst), .CK (clk), .D (n_8), .Q
       (fnd_data[3]));
  DFFRHQX1 \fnd_data_reg[2] (.RN (rst), .CK (clk), .D (n_9), .Q
       (fnd_data[2]));
  OAI2BB1X1 g1299__6161(.A0N (n_0), .A1N (out_ones[7]), .B0 (n_6), .Y
       (n_10));
  OAI2BB1X1 g1300__9315(.A0N (n_0), .A1N (out_ones[2]), .B0 (n_6), .Y
       (n_9));
  OAI2BB1X1 g1301__9945(.A0N (n_0), .A1N (out_ones[3]), .B0 (n_6), .Y
       (n_8));
  OAI2BB1X1 g1302__2883(.A0N (n_0), .A1N (out_ones[4]), .B0 (n_6), .Y
       (n_7));
  NAND2X1 g1303__2346(.A (fnd_sel[0]), .B (n_5), .Y (n_6));
  DFFRHQX1 \fnd_data_reg[6] (.RN (rst), .CK (clk), .D (n_4), .Q
       (fnd_data[6]));
  DFFRHQX1 \fnd_data_reg[5] (.RN (rst), .CK (clk), .D (n_3), .Q
       (fnd_data[5]));
  DFFRHQX1 \fnd_data_reg[1] (.RN (rst), .CK (clk), .D (n_2), .Q
       (fnd_data[1]));
  OAI21X1 g1307__1666(.A0 (value[2]), .A1 (value[1]), .B0 (value[3]),
       .Y (n_5));
  OR2XL g1308__7410(.A (fnd_sel[0]), .B (out_ones[6]), .Y (n_4));
  OR2XL g1309__6417(.A (fnd_sel[0]), .B (out_ones[5]), .Y (n_3));
  NOR2BX1 g1310__5477(.AN (out_ones[1]), .B (fnd_sel[0]), .Y (n_2));
  DFFRHQX1 \fnd_sel_reg[1] (.RN (rst), .CK (clk), .D (fnd_sel[0]), .Q
       (fnd_sel[1]));
  DFFRX1 \fnd_sel_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q
       (fnd_sel[0]), .QN (n_0));
endmodule

module seven_seg_5_70(num, seven_seg);
  input [3:0] num;
  output [7:0] seven_seg;
  wire [3:0] num;
  wire [7:0] seven_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  NAND4XL g317__2398(.A (n_1), .B (n_4), .C (n_6), .D (n_5), .Y
       (seven_seg[1]));
  NAND4XL g318__5107(.A (n_1), .B (n_6), .C (n_11), .D (n_10), .Y
       (seven_seg[4]));
  NAND3BXL g319__6260(.AN (n_8), .B (num[2]), .C (n_1), .Y
       (seven_seg[6]));
  NAND2BXL g320__4319(.AN (seven_seg[0]), .B (n_11), .Y (seven_seg[3]));
  NAND2X1 g321__8428(.A (n_1), .B (n_12), .Y (seven_seg[7]));
  OAI211X1 g322__5526(.A0 (num[0]), .A1 (n_7), .B0 (n_1), .C0 (n_5), .Y
       (seven_seg[2]));
  NAND3BXL g323__6783(.AN (num[0]), .B (n_1), .C (n_7), .Y
       (seven_seg[5]));
  AOI221X1 g324__3680(.A0 (n_0), .A1 (n_3), .B0 (num[0]), .B1 (num[2]),
       .C0 (num[1]), .Y (n_12));
  OR2XL g325__1617(.A (n_0), .B (n_5), .Y (n_10));
  NAND2X1 g326__2802(.A (n_0), .B (n_5), .Y (n_11));
  OAI22X1 g327__1705(.A0 (num[0]), .A1 (num[1]), .B0 (n_0), .B1 (n_2),
       .Y (n_8));
  AOI21X1 g328__5122(.A0 (n_3), .A1 (n_2), .B0 (n_1), .Y
       (seven_seg[0]));
  INVX1 g329(.A (n_6), .Y (n_7));
  NAND2X1 g330__8246(.A (n_3), .B (num[1]), .Y (n_6));
  NAND2XL g331__7098(.A (n_0), .B (num[1]), .Y (n_4));
  NAND2X1 g332__6131(.A (num[2]), .B (n_2), .Y (n_5));
  INVX1 g333(.A (num[2]), .Y (n_3));
  INVX1 g334(.A (num[1]), .Y (n_2));
  INVX1 g335(.A (num[3]), .Y (n_1));
  INVX1 g336(.A (num[0]), .Y (n_0));
endmodule

module seven_seg_68(num, seven_seg);
  input [3:0] num;
  output [7:0] seven_seg;
  wire [3:0] num;
  wire [7:0] seven_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_6;
  OAI211X1 g175__1881(.A0 (n_0), .A1 (n_4), .B0 (n_3), .C0 (n_6), .Y
       (seven_seg[4]));
  OAI211X1 g176__5115(.A0 (n_2), .A1 (num[0]), .B0 (n_3), .C0 (n_4), .Y
       (seven_seg[1]));
  INVX1 g177(.A (n_6), .Y (seven_seg[3]));
  OAI221X1 g178__7482(.A0 (num[2]), .A1 (num[0]), .B0 (n_2), .B1 (n_0),
       .C0 (n_1), .Y (seven_seg[7]));
  OAI221X1 g179__4733(.A0 (num[1]), .A1 (num[0]), .B0 (n_1), .B1 (n_0),
       .C0 (num[2]), .Y (seven_seg[6]));
  OAI2BB1X1 g180__6161(.A0N (n_3), .A1N (n_0), .B0 (n_4), .Y
       (seven_seg[2]));
  NAND2X1 g181__9315(.A (n_0), .B (n_4), .Y (n_6));
  OR2X1 g182__9945(.A (num[0]), .B (n_3), .Y (seven_seg[5]));
  NAND2X1 g183__2883(.A (num[2]), .B (n_1), .Y (n_4));
  NAND2X1 g184__2346(.A (n_2), .B (num[1]), .Y (n_3));
  INVX1 g185(.A (num[2]), .Y (n_2));
  INVX1 g186(.A (num[1]), .Y (n_1));
  INVX1 g187(.A (num[0]), .Y (n_0));
endmodule

module digit_ctrl_36(clk, rst, value, fnd_data, fnd_sel);
  input clk, rst;
  input [5:0] value;
  output [7:0] fnd_data;
  output [1:0] fnd_sel;
  wire clk, rst;
  wire [5:0] value;
  wire [7:0] fnd_data;
  wire [1:0] fnd_sel;
  wire [7:0] out_ones;
  wire [7:0] out_tens;
  wire UNCONNECTED0, UNCONNECTED_HIER_Z, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  seven_seg_5_70 dec_ones(.num ({n_25, n_24, n_23, value[0]}),
       .seven_seg (out_ones));
  seven_seg_68 dec_tens(.num ({UNCONNECTED_HIER_Z, n_28, n_27, n_26}),
       .seven_seg ({out_tens[7:1], UNCONNECTED0}));
  SDFFRHQX1 \fnd_data_reg[7] (.RN (rst), .CK (clk), .D (out_ones[7]),
       .SI (out_tens[7]), .SE (fnd_sel[0]), .Q (fnd_data[7]));
  SDFFRHQX1 \fnd_data_reg[6] (.RN (rst), .CK (clk), .D (out_ones[6]),
       .SI (out_tens[6]), .SE (fnd_sel[0]), .Q (fnd_data[6]));
  SDFFRHQX1 \fnd_data_reg[4] (.RN (rst), .CK (clk), .D (out_ones[4]),
       .SI (out_tens[4]), .SE (fnd_sel[0]), .Q (fnd_data[4]));
  SDFFRHQX1 \fnd_data_reg[2] (.RN (rst), .CK (clk), .D (out_ones[2]),
       .SI (out_tens[2]), .SE (fnd_sel[0]), .Q (fnd_data[2]));
  SDFFRHQX1 \fnd_data_reg[5] (.RN (rst), .CK (clk), .D (out_ones[5]),
       .SI (out_tens[5]), .SE (fnd_sel[0]), .Q (fnd_data[5]));
  SDFFRHQX1 \fnd_data_reg[3] (.RN (rst), .CK (clk), .D (out_ones[3]),
       .SI (out_tens[3]), .SE (fnd_sel[0]), .Q (fnd_data[3]));
  SDFFRHQX1 \fnd_data_reg[1] (.RN (rst), .CK (clk), .D (out_ones[1]),
       .SI (out_tens[1]), .SE (fnd_sel[0]), .Q (fnd_data[1]));
  DFFRHQX1 \fnd_data_reg[0] (.RN (rst), .CK (clk), .D (n_22), .Q
       (fnd_data[0]));
  NOR2BX1 g5017__1666(.AN (out_ones[0]), .B (fnd_sel[0]), .Y (n_22));
  DFFRX1 \fnd_sel_reg[0] (.RN (rst), .CK (clk), .D (n_21), .Q
       (fnd_sel[0]), .QN (n_21));
  DFFRHQX1 \fnd_sel_reg[1] (.RN (rst), .CK (clk), .D (fnd_sel[0]), .Q
       (fnd_sel[1]));
  OAI222X1 g5258__7410(.A0 (n_3), .A1 (n_20), .B0 (value[1]), .B1
       (n_19), .C0 (n_2), .C1 (n_13), .Y (n_23));
  OAI222X1 g5259__6417(.A0 (value[1]), .A1 (n_17), .B0 (n_2), .B1
       (n_20), .C0 (n_9), .C1 (n_12), .Y (n_25));
  OAI211X1 g5260__5477(.A0 (n_3), .A1 (n_18), .B0 (n_12), .C0 (n_19),
       .Y (n_26));
  OAI222X1 g5261__2398(.A0 (n_9), .A1 (n_16), .B0 (n_12), .B1 (n_11),
       .C0 (n_2), .C1 (n_15), .Y (n_24));
  MX2X1 g5262__5107(.A (n_7), .B (n_14), .S0 (value[4]), .Y (n_27));
  AOI22X1 g5263__6260(.A0 (value[1]), .A1 (n_10), .B0 (n_1), .B1 (n_7),
       .Y (n_20));
  AOI22X1 g5264__4319(.A0 (n_3), .A1 (n_10), .B0 (n_8), .B1 (n_5), .Y
       (n_19));
  NOR2BX1 g5265__8428(.AN (n_13), .B (n_7), .Y (n_18));
  NAND2BXL g5266__5526(.AN (n_11), .B (n_5), .Y (n_17));
  AOI221X1 g5267__6783(.A0 (value[5]), .A1 (n_1), .B0 (value[1]), .B1
       (n_0), .C0 (n_10), .Y (n_16));
  AOI21X1 g5268__3680(.A0 (n_1), .A1 (n_6), .B0 (n_5), .Y (n_15));
  OAI2BB1X1 g5269__1617(.A0N (value[2]), .A1N (n_6), .B0 (n_4), .Y
       (n_14));
  NAND2X1 g5270__2802(.A (value[1]), .B (n_5), .Y (n_13));
  NAND2X1 g5271__1705(.A (value[1]), .B (n_7), .Y (n_12));
  AOI2BB1X1 g5272__5122(.A0N (value[3]), .A1N (value[4]), .B0 (n_0), .Y
       (n_28));
  NAND2XL g5273__8246(.A (n_2), .B (n_9), .Y (n_11));
  NOR2X1 g5274__7098(.A (n_7), .B (n_5), .Y (n_10));
  INVX1 g5275(.A (n_8), .Y (n_9));
  INVX1 g5276(.A (n_7), .Y (n_6));
  NOR2BX1 g5277__6131(.AN (value[2]), .B (value[4]), .Y (n_8));
  NOR2X1 g5278__1881(.A (value[3]), .B (n_0), .Y (n_7));
  INVX1 g5279(.A (n_4), .Y (n_5));
  INVX1 g5280(.A (n_3), .Y (n_2));
  NAND2X1 g5281__5115(.A (value[3]), .B (n_0), .Y (n_4));
  NOR2BX1 g5282__7482(.AN (value[4]), .B (value[2]), .Y (n_3));
  INVX1 g5283(.A (value[1]), .Y (n_1));
  INVX1 g5284(.A (value[5]), .Y (n_0));
endmodule

module seven_seg_5_69(num, seven_seg);
  input [3:0] num;
  output [7:0] seven_seg;
  wire [3:0] num;
  wire [7:0] seven_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  NAND4XL g317__4733(.A (n_1), .B (n_4), .C (n_6), .D (n_5), .Y
       (seven_seg[1]));
  NAND4XL g318__6161(.A (n_1), .B (n_6), .C (n_11), .D (n_10), .Y
       (seven_seg[4]));
  NAND3BXL g319__9315(.AN (n_8), .B (num[2]), .C (n_1), .Y
       (seven_seg[6]));
  NAND2BXL g320__9945(.AN (seven_seg[0]), .B (n_11), .Y (seven_seg[3]));
  NAND2X1 g321__2883(.A (n_1), .B (n_12), .Y (seven_seg[7]));
  OAI211X1 g322__2346(.A0 (num[0]), .A1 (n_7), .B0 (n_1), .C0 (n_5), .Y
       (seven_seg[2]));
  NAND3BXL g323__1666(.AN (num[0]), .B (n_1), .C (n_7), .Y
       (seven_seg[5]));
  AOI221X1 g324__7410(.A0 (n_0), .A1 (n_3), .B0 (num[0]), .B1 (num[2]),
       .C0 (num[1]), .Y (n_12));
  OR2XL g325__6417(.A (n_0), .B (n_5), .Y (n_10));
  NAND2X1 g326__5477(.A (n_0), .B (n_5), .Y (n_11));
  OAI22X1 g327__2398(.A0 (num[0]), .A1 (num[1]), .B0 (n_0), .B1 (n_2),
       .Y (n_8));
  AOI21X1 g328__5107(.A0 (n_3), .A1 (n_2), .B0 (n_1), .Y
       (seven_seg[0]));
  INVX1 g329(.A (n_6), .Y (n_7));
  NAND2X1 g330__6260(.A (n_3), .B (num[1]), .Y (n_6));
  NAND2XL g331__4319(.A (n_0), .B (num[1]), .Y (n_4));
  NAND2X1 g332__8428(.A (num[2]), .B (n_2), .Y (n_5));
  INVX1 g333(.A (num[2]), .Y (n_3));
  INVX1 g334(.A (num[1]), .Y (n_2));
  INVX1 g335(.A (num[3]), .Y (n_1));
  INVX1 g336(.A (num[0]), .Y (n_0));
endmodule

module seven_seg(num, seven_seg);
  input [3:0] num;
  output [7:0] seven_seg;
  wire [3:0] num;
  wire [7:0] seven_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_6;
  OAI211X1 g175__5526(.A0 (n_0), .A1 (n_4), .B0 (n_3), .C0 (n_6), .Y
       (seven_seg[4]));
  OAI211X1 g176__6783(.A0 (n_2), .A1 (num[0]), .B0 (n_3), .C0 (n_4), .Y
       (seven_seg[1]));
  INVX1 g177(.A (n_6), .Y (seven_seg[3]));
  OAI221X1 g178__3680(.A0 (num[2]), .A1 (num[0]), .B0 (n_2), .B1 (n_0),
       .C0 (n_1), .Y (seven_seg[7]));
  OAI221X1 g179__1617(.A0 (num[1]), .A1 (num[0]), .B0 (n_1), .B1 (n_0),
       .C0 (num[2]), .Y (seven_seg[6]));
  OAI2BB1X1 g180__2802(.A0N (n_3), .A1N (n_0), .B0 (n_4), .Y
       (seven_seg[2]));
  NAND2X1 g181__1705(.A (n_0), .B (n_4), .Y (n_6));
  OR2X1 g182__5122(.A (num[0]), .B (n_3), .Y (seven_seg[5]));
  NAND2X1 g183__8246(.A (num[2]), .B (n_1), .Y (n_4));
  NAND2X1 g184__7098(.A (n_2), .B (num[1]), .Y (n_3));
  INVX1 g185(.A (num[2]), .Y (n_2));
  INVX1 g186(.A (num[1]), .Y (n_1));
  INVX1 g187(.A (num[0]), .Y (n_0));
endmodule

module digit_ctrl(clk, rst, value, fnd_data, fnd_sel);
  input clk, rst;
  input [5:0] value;
  output [7:0] fnd_data;
  output [1:0] fnd_sel;
  wire clk, rst;
  wire [5:0] value;
  wire [7:0] fnd_data;
  wire [1:0] fnd_sel;
  wire [7:0] out_ones;
  wire [7:0] out_tens;
  wire UNCONNECTED1, UNCONNECTED_HIER_Z0, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  seven_seg_5_69 dec_ones(.num ({n_25, n_24, n_23, value[0]}),
       .seven_seg (out_ones));
  seven_seg dec_tens(.num ({UNCONNECTED_HIER_Z0, n_28, n_27, n_26}),
       .seven_seg ({out_tens[7:1], UNCONNECTED1}));
  SDFFRHQX1 \fnd_data_reg[7] (.RN (rst), .CK (clk), .D (out_ones[7]),
       .SI (out_tens[7]), .SE (fnd_sel[0]), .Q (fnd_data[7]));
  SDFFRHQX1 \fnd_data_reg[6] (.RN (rst), .CK (clk), .D (out_ones[6]),
       .SI (out_tens[6]), .SE (fnd_sel[0]), .Q (fnd_data[6]));
  SDFFRHQX1 \fnd_data_reg[4] (.RN (rst), .CK (clk), .D (out_ones[4]),
       .SI (out_tens[4]), .SE (fnd_sel[0]), .Q (fnd_data[4]));
  SDFFRHQX1 \fnd_data_reg[2] (.RN (rst), .CK (clk), .D (out_ones[2]),
       .SI (out_tens[2]), .SE (fnd_sel[0]), .Q (fnd_data[2]));
  SDFFRHQX1 \fnd_data_reg[5] (.RN (rst), .CK (clk), .D (out_ones[5]),
       .SI (out_tens[5]), .SE (fnd_sel[0]), .Q (fnd_data[5]));
  SDFFRHQX1 \fnd_data_reg[3] (.RN (rst), .CK (clk), .D (out_ones[3]),
       .SI (out_tens[3]), .SE (fnd_sel[0]), .Q (fnd_data[3]));
  SDFFRHQX1 \fnd_data_reg[1] (.RN (rst), .CK (clk), .D (out_ones[1]),
       .SI (out_tens[1]), .SE (fnd_sel[0]), .Q (fnd_data[1]));
  DFFRHQX1 \fnd_data_reg[0] (.RN (rst), .CK (clk), .D (n_22), .Q
       (fnd_data[0]));
  NOR2BX1 g5017__6131(.AN (out_ones[0]), .B (fnd_sel[0]), .Y (n_22));
  DFFRX1 \fnd_sel_reg[0] (.RN (rst), .CK (clk), .D (n_21), .Q
       (fnd_sel[0]), .QN (n_21));
  DFFRHQX1 \fnd_sel_reg[1] (.RN (rst), .CK (clk), .D (fnd_sel[0]), .Q
       (fnd_sel[1]));
  OAI222X1 g5258__1881(.A0 (n_3), .A1 (n_20), .B0 (value[1]), .B1
       (n_19), .C0 (n_2), .C1 (n_13), .Y (n_23));
  OAI222X1 g5259__5115(.A0 (value[1]), .A1 (n_17), .B0 (n_2), .B1
       (n_20), .C0 (n_9), .C1 (n_12), .Y (n_25));
  OAI211X1 g5260__7482(.A0 (n_3), .A1 (n_18), .B0 (n_12), .C0 (n_19),
       .Y (n_26));
  OAI222X1 g5261__4733(.A0 (n_9), .A1 (n_16), .B0 (n_12), .B1 (n_11),
       .C0 (n_2), .C1 (n_15), .Y (n_24));
  MX2X1 g5262__6161(.A (n_7), .B (n_14), .S0 (value[4]), .Y (n_27));
  AOI22X1 g5263__9315(.A0 (value[1]), .A1 (n_10), .B0 (n_1), .B1 (n_7),
       .Y (n_20));
  AOI22X1 g5264__9945(.A0 (n_3), .A1 (n_10), .B0 (n_8), .B1 (n_5), .Y
       (n_19));
  NOR2BX1 g5265__2883(.AN (n_13), .B (n_7), .Y (n_18));
  NAND2BXL g5266__2346(.AN (n_11), .B (n_5), .Y (n_17));
  AOI221X1 g5267__1666(.A0 (value[5]), .A1 (n_1), .B0 (value[1]), .B1
       (n_0), .C0 (n_10), .Y (n_16));
  AOI21X1 g5268__7410(.A0 (n_1), .A1 (n_6), .B0 (n_5), .Y (n_15));
  OAI2BB1X1 g5269__6417(.A0N (value[2]), .A1N (n_6), .B0 (n_4), .Y
       (n_14));
  NAND2X1 g5270__5477(.A (value[1]), .B (n_5), .Y (n_13));
  NAND2X1 g5271__2398(.A (value[1]), .B (n_7), .Y (n_12));
  AOI2BB1X1 g5272__5107(.A0N (value[3]), .A1N (value[4]), .B0 (n_0), .Y
       (n_28));
  NAND2XL g5273__6260(.A (n_2), .B (n_9), .Y (n_11));
  NOR2X1 g5274__4319(.A (n_7), .B (n_5), .Y (n_10));
  INVX1 g5275(.A (n_8), .Y (n_9));
  INVX1 g5276(.A (n_7), .Y (n_6));
  NOR2BX1 g5277__8428(.AN (value[2]), .B (value[4]), .Y (n_8));
  NOR2X1 g5278__5526(.A (value[3]), .B (n_0), .Y (n_7));
  INVX1 g5279(.A (n_4), .Y (n_5));
  INVX1 g5280(.A (n_3), .Y (n_2));
  NAND2X1 g5281__6783(.A (value[3]), .B (n_0), .Y (n_4));
  NOR2BX1 g5282__3680(.AN (value[4]), .B (value[2]), .Y (n_3));
  INVX1 g5283(.A (value[1]), .Y (n_1));
  INVX1 g5284(.A (value[5]), .Y (n_0));
endmodule

module hour(clk, rst, min, hour);
  input clk, rst;
  input [5:0] min;
  output [3:0] hour;
  wire clk, rst;
  wire [5:0] min;
  wire [3:0] hour;
  wire [5:0] pre_min;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  OAI22X1 g853__1617(.A0 (hour[3]), .A1 (n_18), .B0 (n_1), .B1 (n_11),
       .Y (n_21));
  DFFRHQX1 \hour_reg[3] (.RN (rst), .CK (clk), .D (n_20), .Q (hour[3]));
  OAI31X1 g855__2802(.A0 (hour[3]), .A1 (n_1), .A2 (n_16), .B0 (n_14),
       .Y (n_20));
  OAI22X1 g856__1705(.A0 (n_4), .A1 (n_17), .B0 (n_2), .B1 (n_11), .Y
       (n_19));
  AOI22X1 g857__5122(.A0 (n_1), .A1 (n_15), .B0 (hour[2]), .B1 (n_3),
       .Y (n_18));
  DFFRX1 \hour_reg[0] (.RN (rst), .CK (clk), .D (n_13), .Q (hour[0]),
       .QN (n_0));
  MX2XL g859__8246(.A (n_12), .B (hour[0]), .S0 (hour[1]), .Y (n_17));
  INVX1 g860(.A (n_15), .Y (n_16));
  NOR2X1 g861__7098(.A (n_2), .B (n_12), .Y (n_15));
  OAI2BB1X1 g862__6131(.A0N (n_6), .A1N (n_11), .B0 (hour[3]), .Y
       (n_14));
  OAI32X1 g863__1881(.A0 (hour[0]), .A1 (n_4), .A2 (n_10), .B0 (n_0),
       .B1 (n_11), .Y (n_13));
  NAND2X1 g864__5115(.A (hour[0]), .B (n_11), .Y (n_12));
  INVX1 g865(.A (n_11), .Y (n_10));
  NOR2BX1 g866__7482(.AN (n_9), .B (min[4]), .Y (n_11));
  NOR4X1 g867__4733(.A (min[1]), .B (min[2]), .C (min[3]), .D (n_8), .Y
       (n_9));
  OR4X1 g868__6161(.A (n_5), .B (n_7), .C (min[5]), .D (min[0]), .Y
       (n_8));
  NAND4BX1 g869__9315(.AN (pre_min[2]), .B (pre_min[3]), .C
       (pre_min[1]), .D (pre_min[0]), .Y (n_7));
  NAND2X1 g870__9945(.A (n_1), .B (n_3), .Y (n_6));
  NAND2X1 g871__2883(.A (pre_min[4]), .B (pre_min[5]), .Y (n_5));
  DFFRHQX1 \pre_min_reg[0] (.RN (rst), .CK (clk), .D (min[0]), .Q
       (pre_min[0]));
  DFFRHQX1 \pre_min_reg[1] (.RN (rst), .CK (clk), .D (min[1]), .Q
       (pre_min[1]));
  DFFRHQX1 \pre_min_reg[2] (.RN (rst), .CK (clk), .D (min[2]), .Q
       (pre_min[2]));
  DFFRHQX1 \pre_min_reg[5] (.RN (rst), .CK (clk), .D (min[5]), .Q
       (pre_min[5]));
  DFFRHQX1 \pre_min_reg[3] (.RN (rst), .CK (clk), .D (min[3]), .Q
       (pre_min[3]));
  DFFRHQX1 \pre_min_reg[4] (.RN (rst), .CK (clk), .D (min[4]), .Q
       (pre_min[4]));
  AND2X1 g878__2346(.A (hour[3]), .B (hour[2]), .Y (n_4));
  NAND2X1 g879__1666(.A (hour[1]), .B (hour[0]), .Y (n_3));
  DFFRX1 \hour_reg[1] (.RN (rst), .CK (clk), .D (n_19), .Q (hour[1]),
       .QN (n_2));
  DFFRX1 \hour_reg[2] (.RN (rst), .CK (clk), .D (n_21), .Q (hour[2]),
       .QN (n_1));
endmodule

module minute(clk, rst, sec, min);
  input clk, rst;
  input [5:0] sec;
  output [5:0] min;
  wire clk, rst;
  wire [5:0] sec;
  wire [5:0] min;
  wire [5:0] pre_sec;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  DFFRX1 \min_reg[3] (.RN (rst), .CK (clk), .D (n_30), .Q (min[3]), .QN
       (n_2));
  DFFRX1 \min_reg[1] (.RN (rst), .CK (clk), .D (n_26), .Q (min[1]), .QN
       (n_3));
  DFFRX1 \min_reg[2] (.RN (rst), .CK (clk), .D (n_25), .Q (min[2]), .QN
       (n_0));
  MXI2XL g1046__7410(.A (n_18), .B (n_23), .S0 (min[3]), .Y (n_30));
  OAI31X1 g1047__6417(.A0 (min[4]), .A1 (n_2), .A2 (n_18), .B0 (n_27),
       .Y (n_29));
  OAI31X1 g1049__5477(.A0 (min[5]), .A1 (n_6), .A2 (n_18), .B0 (n_24),
       .Y (n_28));
  OAI21X1 g1050__2398(.A0 (n_2), .A1 (n_22), .B0 (min[4]), .Y (n_27));
  OAI22X1 g1051__5107(.A0 (n_12), .A1 (n_21), .B0 (n_3), .B1 (n_16), .Y
       (n_26));
  OAI22X1 g1052__6260(.A0 (n_10), .A1 (n_19), .B0 (n_0), .B1 (n_16), .Y
       (n_25));
  DFFRX1 \min_reg[0] (.RN (rst), .CK (clk), .D (n_20), .Q (min[0]), .QN
       (n_1));
  OAI21X1 g1054__4319(.A0 (n_6), .A1 (n_17), .B0 (min[5]), .Y (n_24));
  AOI2BB1XL g1055__8428(.A0N (min[4]), .A1N (n_9), .B0 (n_22), .Y
       (n_23));
  AOI32X1 g1056__5526(.A0 (min[0]), .A1 (n_3), .A2 (n_16), .B0
       (min[1]), .B1 (n_1), .Y (n_21));
  OAI211X1 g1057__6783(.A0 (min[5]), .A1 (n_9), .B0 (n_8), .C0 (n_16),
       .Y (n_22));
  OAI32X1 g1058__3680(.A0 (min[0]), .A1 (n_12), .A2 (n_15), .B0 (n_1),
       .B1 (n_16), .Y (n_20));
  AOI32X1 g1059__1617(.A0 (n_0), .A1 (n_4), .A2 (n_16), .B0 (min[2]),
       .B1 (n_5), .Y (n_19));
  NAND2X1 g1060__2802(.A (n_9), .B (n_16), .Y (n_18));
  NAND2X1 g1061__1705(.A (n_8), .B (n_16), .Y (n_17));
  INVX1 g1062(.A (n_16), .Y (n_15));
  NOR2BX1 g1063__5122(.AN (n_14), .B (sec[0]), .Y (n_16));
  NOR4X1 g1064__8246(.A (sec[3]), .B (sec[2]), .C (sec[1]), .D (n_13),
       .Y (n_14));
  OR4X1 g1065__7098(.A (n_7), .B (n_11), .C (sec[5]), .D (sec[4]), .Y
       (n_13));
  AND2X1 g1066__6131(.A (n_10), .B (min[2]), .Y (n_12));
  NAND4BX1 g1067__1881(.AN (pre_sec[2]), .B (pre_sec[3]), .C
       (pre_sec[1]), .D (pre_sec[0]), .Y (n_11));
  NOR2BX1 g1068__5115(.AN (min[5]), .B (n_6), .Y (n_10));
  NOR2X1 g1069__7482(.A (n_0), .B (n_5), .Y (n_9));
  NAND2X1 g1070__4733(.A (n_0), .B (n_5), .Y (n_8));
  NAND2X1 g1071__6161(.A (pre_sec[4]), .B (pre_sec[5]), .Y (n_7));
  DFFRHQX1 \pre_sec_reg[1] (.RN (rst), .CK (clk), .D (sec[1]), .Q
       (pre_sec[1]));
  DFFRHQX1 \pre_sec_reg[3] (.RN (rst), .CK (clk), .D (sec[3]), .Q
       (pre_sec[3]));
  DFFRHQX1 \pre_sec_reg[2] (.RN (rst), .CK (clk), .D (sec[2]), .Q
       (pre_sec[2]));
  DFFRHQX1 \pre_sec_reg[4] (.RN (rst), .CK (clk), .D (sec[4]), .Q
       (pre_sec[4]));
  INVX1 g1076(.A (n_5), .Y (n_4));
  DFFRHQX1 \pre_sec_reg[5] (.RN (rst), .CK (clk), .D (sec[5]), .Q
       (pre_sec[5]));
  DFFRHQX1 \pre_sec_reg[0] (.RN (rst), .CK (clk), .D (sec[0]), .Q
       (pre_sec[0]));
  NAND2X1 g1079__9315(.A (min[4]), .B (min[3]), .Y (n_6));
  NAND2X1 g1080__9945(.A (min[1]), .B (min[0]), .Y (n_5));
  DFFRHQX1 \min_reg[5] (.RN (rst), .CK (clk), .D (n_28), .Q (min[5]));
  DFFRHQX1 \min_reg[4] (.RN (rst), .CK (clk), .D (n_29), .Q (min[4]));
endmodule

module second(clk, rst, sec);
  input clk, rst;
  output [5:0] sec;
  wire clk, rst;
  wire [5:0] sec;
  wire [19:0] cnt;
  wire inc_add_26_24_n_0, inc_add_26_24_n_2, inc_add_26_24_n_4,
       inc_add_26_24_n_6, inc_add_26_24_n_9, inc_add_26_24_n_10,
       inc_add_26_24_n_12, inc_add_26_24_n_14;
  wire inc_add_26_24_n_16, inc_add_26_24_n_18, inc_add_26_24_n_21,
       inc_add_26_24_n_22, inc_add_26_24_n_25, inc_add_26_24_n_26,
       inc_add_26_24_n_28, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68;
  DFFRX1 \sec_reg[3] (.RN (rst), .CK (clk), .D (n_47), .Q (sec[3]), .QN
       (n_3));
  DFFRX1 \sec_reg[2] (.RN (rst), .CK (clk), .D (n_46), .Q (sec[2]), .QN
       (n_2));
  OAI21X1 g960__2883(.A0 (n_16), .A1 (n_30), .B0 (n_44), .Y (n_49));
  OAI31X1 g961__2346(.A0 (sec[4]), .A1 (n_12), .A2 (n_30), .B0 (n_45),
       .Y (n_48));
  OAI22X1 g962__1666(.A0 (n_3), .A1 (n_42), .B0 (n_14), .B1 (n_30), .Y
       (n_47));
  OAI32X1 g963__7410(.A0 (sec[2]), .A1 (n_8), .A2 (n_30), .B0 (n_2),
       .B1 (n_42), .Y (n_46));
  DFFRX1 \sec_reg[1] (.RN (rst), .CK (clk), .D (n_40), .Q (sec[1]), .QN
       (n_0));
  DFFRX1 \sec_reg[0] (.RN (rst), .CK (clk), .D (n_41), .Q (sec[0]), .QN
       (n_1));
  NAND2X1 g966__6417(.A (sec[4]), .B (n_43), .Y (n_45));
  NAND2X1 g967__5477(.A (sec[5]), .B (n_43), .Y (n_44));
  OAI2BB1X1 g968__2398(.A0N (n_12), .A1N (n_29), .B0 (n_20), .Y (n_43));
  AOI21X1 g969__5107(.A0 (n_8), .A1 (n_29), .B0 (n_19), .Y (n_42));
  MXI2XL g970__6260(.A (n_30), .B (n_20), .S0 (sec[0]), .Y (n_41));
  OAI22XL g971__4319(.A0 (n_5), .A1 (n_30), .B0 (n_0), .B1 (n_20), .Y
       (n_40));
  DFFRHQX1 \cnt_reg[6] (.RN (rst), .CK (clk), .D (n_35), .Q (cnt[6]));
  DFFRHQX1 \cnt_reg[3] (.RN (rst), .CK (clk), .D (n_31), .Q (cnt[3]));
  DFFRHQX1 \cnt_reg[4] (.RN (rst), .CK (clk), .D (n_38), .Q (cnt[4]));
  DFFRHQX1 \cnt_reg[5] (.RN (rst), .CK (clk), .D (n_36), .Q (cnt[5]));
  DFFRHQX1 \cnt_reg[1] (.RN (rst), .CK (clk), .D (n_22), .Q (cnt[1]));
  DFFRHQX1 \cnt_reg[7] (.RN (rst), .CK (clk), .D (n_34), .Q (cnt[7]));
  DFFRHQX1 \cnt_reg[8] (.RN (rst), .CK (clk), .D (n_33), .Q (cnt[8]));
  DFFRHQX1 \cnt_reg[2] (.RN (rst), .CK (clk), .D (n_37), .Q (cnt[2]));
  DFFRHQX1 \cnt_reg[11] (.RN (rst), .CK (clk), .D (n_21), .Q (cnt[11]));
  DFFRHQX1 \cnt_reg[12] (.RN (rst), .CK (clk), .D (n_24), .Q (cnt[12]));
  DFFRHQX1 \cnt_reg[14] (.RN (rst), .CK (clk), .D (n_26), .Q (cnt[14]));
  DFFRHQX1 \cnt_reg[13] (.RN (rst), .CK (clk), .D (n_27), .Q (cnt[13]));
  DFFRHQX1 \cnt_reg[15] (.RN (rst), .CK (clk), .D (n_25), .Q (cnt[15]));
  DFFRHQX1 \cnt_reg[16] (.RN (rst), .CK (clk), .D (n_28), .Q (cnt[16]));
  DFFRHQX1 \cnt_reg[0] (.RN (rst), .CK (clk), .D (n_23), .Q (cnt[0]));
  DFFRHQX1 \cnt_reg[9] (.RN (rst), .CK (clk), .D (n_32), .Q (cnt[9]));
  DFFRHQX1 \cnt_reg[10] (.RN (rst), .CK (clk), .D (n_39), .Q (cnt[10]));
  NOR2BX1 g989__8428(.AN (n_59), .B (n_20), .Y (n_39));
  NOR2BX1 g990__5526(.AN (n_65), .B (n_20), .Y (n_38));
  NOR2BX1 g991__6783(.AN (n_67), .B (n_20), .Y (n_37));
  NOR2BX1 g992__3680(.AN (n_64), .B (n_20), .Y (n_36));
  NOR2BX1 g993__1617(.AN (n_63), .B (n_20), .Y (n_35));
  NOR2BX1 g994__2802(.AN (n_62), .B (n_20), .Y (n_34));
  NOR2BX1 g995__1705(.AN (n_61), .B (n_20), .Y (n_33));
  NOR2BX1 g996__5122(.AN (n_60), .B (n_20), .Y (n_32));
  NOR2BX1 g997__8246(.AN (n_66), .B (n_20), .Y (n_31));
  INVX1 g998(.A (n_30), .Y (n_29));
  NOR2BX1 g999__7098(.AN (n_53), .B (n_20), .Y (n_28));
  NOR2BX1 g1000__6131(.AN (n_56), .B (n_20), .Y (n_27));
  NOR2BX1 g1001__1881(.AN (n_55), .B (n_20), .Y (n_26));
  NOR2BX1 g1002__5115(.AN (n_54), .B (n_20), .Y (n_25));
  NOR2BX1 g1003__7482(.AN (n_57), .B (n_20), .Y (n_24));
  NOR2X1 g1004__4733(.A (cnt[0]), .B (n_20), .Y (n_23));
  NOR2BX1 g1005__6161(.AN (n_68), .B (n_20), .Y (n_22));
  NOR2BX1 g1006__9315(.AN (n_58), .B (n_20), .Y (n_21));
  OAI21X1 g1007__9945(.A0 (n_3), .A1 (n_13), .B0 (n_20), .Y (n_30));
  INVX1 g1008(.A (n_20), .Y (n_19));
  AND3X1 g1009__2883(.A (cnt[15]), .B (cnt[16]), .C (n_18), .Y (n_20));
  NAND3BXL g1010__2346(.AN (cnt[14]), .B (n_10), .C (n_17), .Y (n_18));
  NAND4BX1 g1011__1666(.AN (n_15), .B (cnt[7]), .C (cnt[10]), .D
       (cnt[9]), .Y (n_17));
  AOI21X1 g1012__7410(.A0 (sec[4]), .A1 (n_11), .B0 (sec[5]), .Y
       (n_16));
  AOI211XL g1013__6417(.A0 (cnt[0]), .A1 (n_7), .B0 (cnt[6]), .C0
       (cnt[5]), .Y (n_15));
  AOI22X1 g1014__5477(.A0 (n_3), .A1 (n_9), .B0 (sec[3]), .B1 (n_2), .Y
       (n_14));
  OAI211X1 g1015__2398(.A0 (sec[2]), .A1 (n_4), .B0 (sec[4]), .C0
       (sec[5]), .Y (n_13));
  INVX1 g1016(.A (n_12), .Y (n_11));
  NAND2X1 g1017__5107(.A (sec[3]), .B (n_9), .Y (n_12));
  NOR4X1 g1018__6260(.A (cnt[11]), .B (cnt[12]), .C (cnt[13]), .D
       (n_6), .Y (n_10));
  NOR2X1 g1019__4319(.A (n_2), .B (n_8), .Y (n_9));
  INVX1 g1020(.A (n_4), .Y (n_8));
  AND4XL g1021__8428(.A (cnt[2]), .B (cnt[1]), .C (cnt[3]), .D
       (cnt[4]), .Y (n_7));
  AND3XL g1022__5526(.A (cnt[9]), .B (cnt[8]), .C (cnt[10]), .Y (n_6));
  MX2XL g1023__6783(.A (n_0), .B (sec[1]), .S0 (sec[0]), .Y (n_5));
  NOR2X1 g1024__3680(.A (n_0), .B (n_1), .Y (n_4));
  XNOR2X1 inc_add_26_24_g212__1617(.A (cnt[16]), .B
       (inc_add_26_24_n_28), .Y (n_53));
  OA21X1 inc_add_26_24_g213__2802(.A0 (cnt[15]), .A1
       (inc_add_26_24_n_26), .B0 (inc_add_26_24_n_28), .Y (n_54));
  NAND2X1 inc_add_26_24_g214__1705(.A (cnt[15]), .B
       (inc_add_26_24_n_26), .Y (inc_add_26_24_n_28));
  AOI2BB1XL inc_add_26_24_g215__5122(.A0N (cnt[14]), .A1N
       (inc_add_26_24_n_25), .B0 (inc_add_26_24_n_26), .Y (n_55));
  AND2XL inc_add_26_24_g216__8246(.A (cnt[14]), .B
       (inc_add_26_24_n_25), .Y (inc_add_26_24_n_26));
  ADDHX1 inc_add_26_24_g217__7098(.A (cnt[13]), .B
       (inc_add_26_24_n_22), .CO (inc_add_26_24_n_25), .S (n_56));
  AOI2BB1XL inc_add_26_24_g218__6131(.A0N (cnt[12]), .A1N
       (inc_add_26_24_n_21), .B0 (inc_add_26_24_n_22), .Y (n_57));
  AND2XL inc_add_26_24_g219__1881(.A (cnt[12]), .B
       (inc_add_26_24_n_21), .Y (inc_add_26_24_n_22));
  ADDHX1 inc_add_26_24_g220__5115(.A (cnt[11]), .B
       (inc_add_26_24_n_18), .CO (inc_add_26_24_n_21), .S (n_58));
  AOI2BB1XL inc_add_26_24_g221__7482(.A0N (cnt[10]), .A1N
       (inc_add_26_24_n_16), .B0 (inc_add_26_24_n_18), .Y (n_59));
  AND2XL inc_add_26_24_g222__4733(.A (cnt[10]), .B
       (inc_add_26_24_n_16), .Y (inc_add_26_24_n_18));
  AOI2BB1XL inc_add_26_24_g223__6161(.A0N (cnt[9]), .A1N
       (inc_add_26_24_n_14), .B0 (inc_add_26_24_n_16), .Y (n_60));
  AND2XL inc_add_26_24_g224__9315(.A (cnt[9]), .B (inc_add_26_24_n_14),
       .Y (inc_add_26_24_n_16));
  XNOR2X1 inc_add_26_24_g225__9945(.A (cnt[8]), .B
       (inc_add_26_24_n_12), .Y (n_61));
  NOR2BX1 inc_add_26_24_g226__2883(.AN (cnt[8]), .B
       (inc_add_26_24_n_12), .Y (inc_add_26_24_n_14));
  OA21X1 inc_add_26_24_g227__2346(.A0 (cnt[7]), .A1
       (inc_add_26_24_n_10), .B0 (inc_add_26_24_n_12), .Y (n_62));
  NAND2X1 inc_add_26_24_g228__1666(.A (cnt[7]), .B
       (inc_add_26_24_n_10), .Y (inc_add_26_24_n_12));
  AOI2BB1XL inc_add_26_24_g229__7410(.A0N (cnt[6]), .A1N
       (inc_add_26_24_n_9), .B0 (inc_add_26_24_n_10), .Y (n_63));
  AND2XL inc_add_26_24_g230__6417(.A (cnt[6]), .B (inc_add_26_24_n_9),
       .Y (inc_add_26_24_n_10));
  ADDHX1 inc_add_26_24_g231__5477(.A (cnt[5]), .B (inc_add_26_24_n_6),
       .CO (inc_add_26_24_n_9), .S (n_64));
  AOI2BB1XL inc_add_26_24_g232__2398(.A0N (cnt[4]), .A1N
       (inc_add_26_24_n_4), .B0 (inc_add_26_24_n_6), .Y (n_65));
  AND2XL inc_add_26_24_g233__5107(.A (cnt[4]), .B (inc_add_26_24_n_4),
       .Y (inc_add_26_24_n_6));
  AOI2BB1XL inc_add_26_24_g234__6260(.A0N (cnt[3]), .A1N
       (inc_add_26_24_n_2), .B0 (inc_add_26_24_n_4), .Y (n_66));
  AND2XL inc_add_26_24_g235__4319(.A (cnt[3]), .B (inc_add_26_24_n_2),
       .Y (inc_add_26_24_n_4));
  AOI2BB1XL inc_add_26_24_g236__8428(.A0N (cnt[2]), .A1N
       (inc_add_26_24_n_0), .B0 (inc_add_26_24_n_2), .Y (n_67));
  AND2XL inc_add_26_24_g237__5526(.A (cnt[2]), .B (inc_add_26_24_n_0),
       .Y (inc_add_26_24_n_2));
  AOI2BB1XL inc_add_26_24_g238__6783(.A0N (cnt[0]), .A1N (cnt[1]), .B0
       (inc_add_26_24_n_0), .Y (n_68));
  AND2XL inc_add_26_24_g239__3680(.A (cnt[0]), .B (cnt[1]), .Y
       (inc_add_26_24_n_0));
  DFFRHQX1 \sec_reg[5] (.RN (rst), .CK (clk), .D (n_49), .Q (sec[5]));
  DFFRHQX1 \sec_reg[4] (.RN (rst), .CK (clk), .D (n_48), .Q (sec[4]));
endmodule

module digtimer(rst, clk, o_sec, o_min, o_hour, seg1_data, seg1_sel,
     seg2_data, seg2_sel, seg3_data, seg3_sel);
  input rst, clk;
  output [5:0] o_sec, o_min;
  output [3:0] o_hour;
  output [7:0] seg1_data, seg2_data, seg3_data;
  output [1:0] seg1_sel, seg2_sel, seg3_sel;
  wire rst, clk;
  wire [5:0] o_sec, o_min;
  wire [3:0] o_hour;
  wire [7:0] seg1_data, seg2_data, seg3_data;
  wire [1:0] seg1_sel, seg2_sel, seg3_sel;
  wire UNCONNECTED2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2;
  assign seg1_data[0] = 1'b0;
  digit_ctrl_2 ctrl_hour(.clk (clk), .rst (rst), .value
       ({UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, o_hour}), .fnd_data
       ({seg1_data[7:1], UNCONNECTED2}), .fnd_sel (seg1_sel));
  digit_ctrl_36 ctrl_min(.clk (clk), .rst (rst), .value (o_min),
       .fnd_data (seg2_data), .fnd_sel (seg2_sel));
  digit_ctrl ctrl_sec(.clk (clk), .rst (rst), .value (o_sec), .fnd_data
       (seg3_data), .fnd_sel (seg3_sel));
  hour ut_hour(.clk (clk), .rst (rst), .min (o_min), .hour (o_hour));
  minute ut_min(.clk (clk), .rst (rst), .sec (o_sec), .min (o_min));
  second ut_sec(.clk (clk), .rst (rst), .sec (o_sec));
endmodule

