
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:20:17 KST (Jul  7 2026 18:20:17 UTC)

// Verification Directory fv/data_bus_driver 

module data_bus_driver(i_in1, i_in2, i_en1, i_en2, o_bus_data);
  input [7:0] i_in1, i_in2;
  input i_en1, i_en2;
  output [7:0] o_bus_data;
  wire [7:0] i_in1, i_in2;
  wire i_en1, i_en2;
  wire [7:0] o_bus_data;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_36;
  TBUFXL g7__2398(.A (n_5), .OE (n_36), .Y (o_bus_data[5]));
  TBUFXL g2__5107(.A (n_3), .OE (n_36), .Y (o_bus_data[6]));
  TBUFXL g6__6260(.A (n_2), .OE (n_36), .Y (o_bus_data[7]));
  TBUFXL g8__4319(.A (n_7), .OE (n_36), .Y (o_bus_data[4]));
  TBUFXL g11__8428(.A (n_1), .OE (n_36), .Y (o_bus_data[1]));
  TBUFXL g10__5526(.A (n_4), .OE (n_36), .Y (o_bus_data[2]));
  TBUFXL g9__6783(.A (n_6), .OE (n_36), .Y (o_bus_data[3]));
  TBUFXL g12__3680(.A (n_8), .OE (n_36), .Y (o_bus_data[0]));
  MX2X1 g250__2802(.A (i_in2[0]), .B (i_in1[0]), .S0 (i_en1), .Y (n_8));
  MX2X1 g249__1705(.A (i_in2[4]), .B (i_in1[4]), .S0 (i_en1), .Y (n_7));
  MX2X1 g253__5122(.A (i_in2[3]), .B (i_in1[3]), .S0 (i_en1), .Y (n_6));
  MX2X1 g246__8246(.A (i_in2[5]), .B (i_in1[5]), .S0 (i_en1), .Y (n_5));
  MX2X1 g245__7098(.A (i_in2[2]), .B (i_in1[2]), .S0 (i_en1), .Y (n_4));
  MX2X1 g252__6131(.A (i_in2[6]), .B (i_in1[6]), .S0 (i_en1), .Y (n_3));
  MX2X1 g251__1881(.A (i_in2[7]), .B (i_in1[7]), .S0 (i_en1), .Y (n_2));
  MX2X1 g247__5115(.A (i_in2[1]), .B (i_in1[1]), .S0 (i_en1), .Y (n_1));
  CLKXOR2X1 g2(.A (i_en1), .B (i_en2), .Y (n_36));
endmodule

