
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:22:56 KST (Jul  7 2026 18:22:56 UTC)

// Verification Directory fv/bidir_bus 

module bidir_bus(i_data_to_bus, i_send, i_rcv, io_bus_data,
     o_data_from_bus);
  input [7:0] i_data_to_bus;
  input i_send, i_rcv;
  output [7:0] o_data_from_bus;
  inout [7:0] io_bus_data;
  wire [7:0] i_data_to_bus;
  wire i_send, i_rcv;
  wire [7:0] o_data_from_bus;
  wire [7:0] io_bus_data;
  TBUFXL g15__2398(.A (io_bus_data[5]), .OE (i_rcv), .Y
       (o_data_from_bus[5]));
  TBUFXL g14__5107(.A (io_bus_data[6]), .OE (i_rcv), .Y
       (o_data_from_bus[6]));
  TBUFXL g13__6260(.A (io_bus_data[7]), .OE (i_rcv), .Y
       (o_data_from_bus[7]));
  TBUFXL g16__4319(.A (io_bus_data[4]), .OE (i_rcv), .Y
       (o_data_from_bus[4]));
  TBUFXL g19__8428(.A (io_bus_data[1]), .OE (i_rcv), .Y
       (o_data_from_bus[1]));
  TBUFXL g18__5526(.A (io_bus_data[2]), .OE (i_rcv), .Y
       (o_data_from_bus[2]));
  TBUFXL g17__6783(.A (io_bus_data[3]), .OE (i_rcv), .Y
       (o_data_from_bus[3]));
  TBUFXL g20__3680(.A (io_bus_data[0]), .OE (i_rcv), .Y
       (o_data_from_bus[0]));
  TBUFX1 g1__1617(.A (i_data_to_bus[7]), .OE (i_send), .Y
       (io_bus_data[7]));
  TBUFX1 g12__2802(.A (i_data_to_bus[0]), .OE (i_send), .Y
       (io_bus_data[0]));
  TBUFX1 g7__1705(.A (i_data_to_bus[5]), .OE (i_send), .Y
       (io_bus_data[5]));
  TBUFX1 g6__5122(.A (i_data_to_bus[6]), .OE (i_send), .Y
       (io_bus_data[6]));
  TBUFX1 g11__8246(.A (i_data_to_bus[1]), .OE (i_send), .Y
       (io_bus_data[1]));
  TBUFX1 g9__7098(.A (i_data_to_bus[3]), .OE (i_send), .Y
       (io_bus_data[3]));
  TBUFX1 g10__6131(.A (i_data_to_bus[2]), .OE (i_send), .Y
       (io_bus_data[2]));
  TBUFX1 g8__1881(.A (i_data_to_bus[4]), .OE (i_send), .Y
       (io_bus_data[4]));
endmodule

