
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 02:28:05 KST (Jul  7 2026 17:28:05 UTC)

// Verification Directory fv/MUX 

module MUX(i_in1, i_in2, i_in3, i_in4, i_sel, o_out);
  input i_in1, i_in2, i_in3, i_in4;
  input [1:0] i_sel;
  output [2:0] o_out;
  wire i_in1, i_in2, i_in3, i_in4;
  wire [1:0] i_sel;
  wire [2:0] o_out;
  assign o_out[1] = 1'b0;
  assign o_out[2] = 1'b0;
  MX4XL g90__2398(.A (i_in1), .B (i_in4), .C (i_in2), .D (i_in3), .S0
       (i_sel[1]), .S1 (i_sel[0]), .Y (o_out[0]));
endmodule

