
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 02:37:32 KST (Jul  7 2026 17:37:32 UTC)

// Verification Directory fv/interrupt 

module interrupt(i_int_ack, i_int_address, o_int_req, o_int_id);
  input i_int_ack;
  input [7:0] i_int_address;
  output o_int_req;
  output [2:0] o_int_id;
  wire i_int_ack;
  wire [7:0] i_int_address;
  wire o_int_req;
  wire [2:0] o_int_id;
  wire n_0, n_1, n_2, n_4, n_6, n_7, n_11, n_22;
  AOI2BB1XL g304__2398(.A0N (i_int_address[7]), .A1N (n_11), .B0
       (i_int_ack), .Y (o_int_id[0]));
  AOI2BB1XL g307__5107(.A0N (i_int_address[5]), .A1N (n_6), .B0
       (i_int_address[6]), .Y (n_11));
  NOR2XL g305__6260(.A (i_int_ack), .B (n_22), .Y (o_int_req));
  NOR2BX1 g306__4319(.AN (n_7), .B (i_int_ack), .Y (o_int_id[1]));
  OAI31X1 g310__5526(.A0 (i_int_address[5]), .A1 (i_int_address[4]),
       .A2 (n_2), .B0 (n_0), .Y (n_7));
  AOI2BB1XL g311__6783(.A0N (i_int_address[3]), .A1N (n_1), .B0
       (i_int_address[4]), .Y (n_6));
  NOR2BX1 g309__3680(.AN (n_4), .B (i_int_ack), .Y (o_int_id[2]));
  OR4X1 g312__1617(.A (i_int_address[6]), .B (i_int_address[7]), .C
       (i_int_address[4]), .D (i_int_address[5]), .Y (n_4));
  NOR2XL g314__2802(.A (i_int_address[2]), .B (i_int_address[3]), .Y
       (n_2));
  NOR2BX1 g315__1705(.AN (i_int_address[1]), .B (i_int_address[2]), .Y
       (n_1));
  NOR2XL g316__5122(.A (i_int_address[6]), .B (i_int_address[7]), .Y
       (n_0));
  NOR4BX1 g2(.AN (n_2), .B (i_int_address[0]), .C (i_int_address[1]),
       .D (n_4), .Y (n_22));
endmodule

