
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 02:44:57 KST (Jul  7 2026 17:44:57 UTC)

// Verification Directory fv/bcd_to_7seg 

module bcd_to_7seg(i_input, o_output);
  input [3:0] i_input;
  output [6:0] o_output;
  wire [3:0] i_input;
  wire [6:0] o_output;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_18;
  wire n_19, n_24;
  TLATX1 \o_output_reg[0] (.G (n_19), .D (n_18), .Q (o_output[0]), .QN
       (UNCONNECTED));
  TLATX1 \o_output_reg[2] (.G (n_19), .D (n_24), .Q (o_output[2]), .QN
       (UNCONNECTED0));
  TLATX1 \o_output_reg[3] (.G (n_19), .D (n_16), .Q (o_output[3]), .QN
       (UNCONNECTED1));
  NAND2BXL g286__2398(.AN (i_input[3]), .B (n_12), .Y (n_18));
  OAI211X1 g291__6260(.A0 (n_11), .A1 (n_13), .B0 (n_2), .C0 (n_8), .Y
       (n_16));
  TLATX1 \o_output_reg[6] (.G (n_19), .D (n_15), .Q (o_output[6]), .QN
       (UNCONNECTED2));
  TLATX1 \o_output_reg[1] (.G (n_19), .D (n_14), .Q (o_output[1]), .QN
       (UNCONNECTED3));
  NAND2XL g289__4319(.A (n_6), .B (n_4), .Y (n_15));
  OAI211X1 g295__8428(.A0 (i_input[0]), .A1 (n_10), .B0 (n_0), .C0
       (n_13), .Y (n_14));
  TLATX1 \o_output_reg[4] (.G (n_19), .D (n_5), .Q (o_output[4]), .QN
       (UNCONNECTED4));
  TLATX1 \o_output_reg[5] (.G (n_19), .D (n_7), .Q (o_output[5]), .QN
       (UNCONNECTED5));
  AOI221X1 g290__5526(.A0 (i_input[2]), .A1 (n_11), .B0 (i_input[0]),
       .B1 (n_10), .C0 (n_3), .Y (n_12));
  NAND2XL g299__6783(.A (n_11), .B (n_13), .Y (n_8));
  OAI221X1 g297__3680(.A0 (i_input[0]), .A1 (i_input[1]), .B0 (n_6),
       .B1 (n_11), .C0 (i_input[2]), .Y (n_7));
  NAND2XL g298__1617(.A (n_11), .B (n_10), .Y (n_5));
  AOI221X1 g294__2802(.A0 (i_input[0]), .A1 (i_input[2]), .B0 (n_1),
       .B1 (n_11), .C0 (i_input[3]), .Y (n_4));
  INVXL g301(.A (n_3), .Y (n_13));
  INVXL g303(.A (n_10), .Y (n_2));
  OAI21XL g300__1705(.A0 (i_input[1]), .A1 (i_input[2]), .B0
       (i_input[3]), .Y (n_19));
  NOR2XL g302__5122(.A (i_input[1]), .B (n_1), .Y (n_3));
  NOR2XL g304__8246(.A (i_input[2]), .B (n_6), .Y (n_10));
  INVXL g305(.A (i_input[3]), .Y (n_0));
  INVXL g306(.A (i_input[0]), .Y (n_11));
  INVXL g308(.A (i_input[2]), .Y (n_1));
  INVXL g307(.A (i_input[1]), .Y (n_6));
  NAND2BX1 g2(.AN (i_input[3]), .B (n_8), .Y (n_24));
endmodule

