
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:15:14 KST (Jul  7 2026 18:15:14 UTC)

// Verification Directory fv/data_bus_driver 

module data_bus_driver(i_in1, i_in2, i_en1, i_en2, o_bus_data);
  input [7:0] i_in1, i_in2;
  input i_en1, i_en2;
  output [7:0] o_bus_data;
  wire [7:0] i_in1, i_in2;
  wire i_en1, i_en2;
  wire [7:0] o_bus_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_16;
  TBUFXL g9__2398(.A (n_2), .OE (n_16), .Y (o_bus_data[0]));
  TBUFXL g3__5107(.A (n_9), .OE (n_16), .Y (o_bus_data[6]));
  TBUFXL g2__6260(.A (n_3), .OE (n_16), .Y (o_bus_data[7]));
  TBUFXL g4__4319(.A (n_4), .OE (n_16), .Y (o_bus_data[5]));
  TBUFXL g7__8428(.A (n_8), .OE (n_16), .Y (o_bus_data[2]));
  TBUFXL g6__5526(.A (n_0), .OE (n_16), .Y (o_bus_data[3]));
  TBUFXL g5__6783(.A (n_1), .OE (n_16), .Y (o_bus_data[4]));
  TBUFXL g8__3680(.A (n_5), .OE (n_16), .Y (o_bus_data[1]));
  AO22X1 g305__1617(.A0 (i_in1[6]), .A1 (n_7), .B0 (i_in2[6]), .B1
       (n_6), .Y (n_9));
  AO22X1 g302__2802(.A0 (i_in1[2]), .A1 (n_7), .B0 (i_in2[2]), .B1
       (n_6), .Y (n_8));
  AO22X1 g301__1705(.A0 (i_in1[1]), .A1 (n_7), .B0 (i_in2[1]), .B1
       (n_6), .Y (n_5));
  AO22X1 g303__5122(.A0 (i_in1[5]), .A1 (n_7), .B0 (i_in2[5]), .B1
       (n_6), .Y (n_4));
  AO22X1 g304__8246(.A0 (i_in1[7]), .A1 (n_7), .B0 (i_in2[7]), .B1
       (n_6), .Y (n_3));
  AO22X1 g307__7098(.A0 (i_in1[0]), .A1 (n_7), .B0 (i_in2[0]), .B1
       (n_6), .Y (n_2));
  AO22X1 g306__6131(.A0 (i_in1[4]), .A1 (n_7), .B0 (i_in2[4]), .B1
       (n_6), .Y (n_1));
  AO22X1 g308__1881(.A0 (i_in1[3]), .A1 (n_7), .B0 (i_in2[3]), .B1
       (n_6), .Y (n_0));
  OR2X1 g309__5115(.A (n_7), .B (n_6), .Y (n_16));
  NOR2BX1 g310__7482(.AN (i_en1), .B (i_en2), .Y (n_7));
  NOR2BX1 g311__4733(.AN (i_en2), .B (i_en1), .Y (n_6));
endmodule

